// src/app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import ScrollToTopButton from './components/ScrollToTopButton'; // Importera knappen
import "./styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Placera ScrollToTopButton här så att den finns tillgänglig på alla sidor */}
        <main>{children}</main>

        {/* Lägg till knappen för att rulla upp */}
        <ScrollToTopButton />
      </body>
    </html>
  );
}
